#!/bin/sh
APPDIR="$(git rev-parse --show-toplevel)/apps/vscode"
HOSTTYPE="$(uname -s)"
CODE=""
CONFDIR=${HOME}
if [ -z ${CODE} ] && [ "${HOSTTYPE}" = "Darwin" ]; then
    CODE="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
    CONFDIR="${HOME}/Library/Application Support/Code/User"
fi

# Abort if code doesn't exist
which "${CODE}" || exit 0

if [ "${HOSTTYPE}" = "Darwin" ]; then
    CONFFILE="${CONFDIR}/settings.json"
    [ -f "${CONFFILE}" ] && mv "${CONFFILE}" "${CONFFILE}-old"
    ln -s "${APPDIR}/settings.json" "${CONFDIR}/settings.json"
fi

while read -r extension; do
    code --install-extension "${extension}"
done < "${APPDIR}/extensions"