#!/bin/bash
COMPLETION_DIRS=""
DOTFILES_BC="${HOME}/.bash_completions"
if [ -d "${DOTFILES_BC}" ]; then
    COMPLETION_DIRS="${DOTFILES_BC}"
fi
if [ "$(uname)" = "Darwin" ]; then
    COMPLETION_DIRS="${COMPLETION_DIRS} /usr/local/etc/bash_completion.d"
fi

load_completions() {
    # ${1}: directory/file to load
    if [ -d "${1}" ]; then
        for o in "${1}"/*; do
            [ -f "${o}" ] && . "${o}"
            # Disabled recursing, since the helpers dir on a Mac is full of Perl
            # if [ -d "${o}" ]; then
            #     load_completions "${o}"
            # else
            #     . "${o}"
            # fi
        done
    fi
}
for dir in ${COMPLETION_DIRS}; do
    load_completions "${dir}"
done
