#!/bin/bash
#~/.bashrc

# Test for an interactive shell.  There is no need to set anything else
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

test -e "/etc/profile" && source "/etc/profile"

if [ "${TERM_PROGRAM}" = "iTerm.app" ]; then
    test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
    test -e "${HOME}/.bashrc_functions" && source "${HOME}/.bashrc_functions"
fi

# Do this early, so we get magic local aliases
# but after we source the local profile, otherwise we might get overriden
test -e  "$HOME/.bashrc.local" && source "$HOME/.bashrc.local"

[ -f "${HOME}/.dotfiles/apps/bash/subtrees/git-prompt/gitprompt.sh" ] && source "${HOME}/.dotfiles/apps/bash/subtrees/git-prompt/gitprompt.sh"

# Mostly for MacOS, but yes
[ -f /usr/local/etc/bash_completion ] && source /usr/local/etc/bash_completion

if [[ ${EUID} == 0 ]] ; then
    export PS1="[\[\033[1;31m\]\$(uname)\[\033[m\]:\[\033[32m\]\h\[\033[m\]]\[\033[1;31m\]\u\[\033[m\]:\[\033[33;1m\]\w\[\033[m\]\$ "
else
    export PS1="[\[\033[1;31m\]\$(uname)\[\033[m\]:\[\033[32m\]\h\[\033[m\]]\[\033[36m\]\u\[\033[m\]:\[\033[33;1m\]\w\[\033[m\]\$ "
fi

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

shopt -s checkwinsize
shopt -s no_empty_cmd_completion
shopt -s histappend

if [ "$(uname)" == 'Darwin' ]; then
    alias ls='ls -GFh'
else
    alias ls='ls -Fh --color=auto'
fi
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias grep='grep --color=auto --exclude-dir=.git --exclude-dir=.svn --binary-files=without-match'
export CSCOPE_DB=$HOME/.cscope.out
export PYCSCOPE_DB=$HOME/.pycscope.out
export ERLCSCOPE_DB=$HOME/.erlcscope.out

export LESSCOLOR=yes
export LESSOPEN="|lesspipe %s"
export EDITOR=vim

# Add titles to Terminal windows
export PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" $(echo ${PWD} | awk -v home="${HOME}" "{sub(home,\"~\");print}") "$0"'

# Other aliaii
alias docker-clean-untagged="docker images --no-trunc | grep '<none>' | awk '{ print \$3 }' | xargs docker rmi"
alias docker-clean-dead="docker ps --filter status=dead --filter status=exited -aq | xargs docker rm -v"
alias docker-clean-volumes="docker volume ls -qf dangling=true | xargs docker volume rm"

# Kubernetes
alias kc="kubectl"
alias kube-gc="kubectl config get-contexts"
alias kube-uc="kubectl config use-context"

# Elongate bash_history
HISTSIZE=5000
HISTFILESIZE=10000
# Enforce history appending
shopt -s histappend


# Add some paths
# User-custom bin
if [ -d "${HOME}/bin" ]; then
    export PATH="${HOME}/bin:${PATH}"
fi
# Default Go bin
if [ -d "${HOME}/go/bin" ]; then
    export PATH="${HOME}/go/bin:${PATH}"
fi
# Default Haskell cabal bin
if [ -d "${HOME}/.cabal/bin" ]; then
    export PATH="${HOME}/.cabal/bin:${PATH}"
fi
# Default rebar3 bin
if [ -d "${HOME}/.cache/rebar3/bin" ]; then
    export PATH="${HOME}/.cache/rebar3/bin:${PATH}"
fi
# Default VSCode directory on a Mac
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
    export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi

VENV_WRAPPER="$(which virtualenvwrapper.sh 2> /dev/null)"
if [ -f "$VENV_WRAPPER" ]; then
    export WORKON_HOME="$HOME/virtualenvs"
    if [ ! -d "$WORKON_HOME" ]; then
        mkdir "$WORKON_HOME"
    fi
    source "$VENV_WRAPPER"
fi
