#!/bin/bash
#~/.bashrc
# shellcheck disable=SC1090,SC1117

# Test for an interactive shell.  There is no need to set anything else
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

UNAME="$(uname)"

test -e "/etc/profile" && source "/etc/profile"

if [ "${TERM_PROGRAM}" = "iTerm.app" ]; then
    test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
    test -e "${HOME}/.bashrc_functions" && source "${HOME}/.bashrc_functions"
fi

# Do this early, so we get magic local aliases
# but after we source the local profile, otherwise we might get overriden
test -e  "$HOME/.bashrc.local" && source "$HOME/.bashrc.local"

# set up bash completion
test -e "${HOME}/.bash_completion" && source "${HOME}/.bash_completion"

PS1_START="[\[\033[1;31m\]\${UNAME}\[\033[m\]:\[\033[32m\]\h\[\033[m\]]"
PS1_DIR="\[\033[33;1m\]\w\[\033[m\]"
if [[ ${EUID} == 0 ]] ; then
    PS1_USER="\[\033[1;31m\]\u\[\033[m\]"
    PS1_SUFFIX="# "
else
    PS1_USER="\[\033[36m\]\u\[\033[m\]"
    PS1_SUFFIX="\$ "
fi
export PS1="${PS1_START}${PS1_USER}:${PS1_DIR}${PS1_SUFFIX}"

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

shopt -s checkwinsize
shopt -s no_empty_cmd_completion
shopt -s histappend

if [ "${UNAME}" == 'Darwin' ]; then
    alias ls='ls -GFh'
else
    alias ls='ls -Fh --color=auto'
fi
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias grep='grep --color=auto --exclude-dir=.git --exclude-dir=.svn --binary-files=without-match'
export CSCOPE_DB=$HOME/.cscope.out
export PYCSCOPE_DB=$HOME/.pycscope.out
export ERLCSCOPE_DB=$HOME/.erlcscope.out

export LESSCOLOR=yes
export LESSOPEN="|lesspipe %s"
export EDITOR=vim

# Add titles to Terminal windows
export PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" $(echo ${PWD} | awk -v home="${HOME}" "{sub(home,\"~\");print}") "$0"'

# Other aliaii
# shellcheck disable=SC2142
alias docker-clean-untagged="docker images --no-trunc | grep '<none>' | awk '{ print \$3 }' | xargs docker rmi"
alias docker-clean-dead="docker ps --filter status=dead --filter status=exited -aq | xargs docker rm -v"
alias docker-clean-volumes="docker volume ls -qf dangling=true | xargs docker volume rm"

# Kubernetes
alias kc="kubectl"
alias kube-gc="kubectl config get-contexts"
alias kube-uc="kubectl config use-context"

# Elongate bash_history
HISTSIZE=5000
HISTFILESIZE=10000
# Enforce history appending
shopt -s histappend


# Add some paths
# User-custom bin
if [ -d "${HOME}/bin" ]; then
    export PATH="${HOME}/bin:${PATH}"
fi
# Default Go bin
if [ -d "${HOME}/go/bin" ]; then
    export PATH="${HOME}/go/bin:${PATH}"
fi
# Default Haskell cabal bin
if [ -d "${HOME}/.cabal/bin" ]; then
    export PATH="${HOME}/.cabal/bin:${PATH}"
fi
# Default rebar3 bin
if [ -d "${HOME}/.cache/rebar3/bin" ]; then
    export PATH="${HOME}/.cache/rebar3/bin:${PATH}"
fi
# Default VSCode directories on a Mac
if [ -d "/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin" ]; then
    export PATH="$PATH:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin"
fi
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
    export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi

VENV_WRAPPER="$(which virtualenvwrapper.sh 2> /dev/null)"
if [ -f "$VENV_WRAPPER" ]; then
    export WORKON_HOME="$HOME/virtualenvs"
    if [ ! -d "$WORKON_HOME" ]; then
        mkdir "$WORKON_HOME"
    fi
    source "$VENV_WRAPPER"
fi


PYENV_BASE="${HOME}/.pyenv"
PYENV_BIN="${PYENV_BASE}/bin"
PYENV="$(which pyenv 2> /dev/null)"
if [ -d "${PYENV_BIN}" ]; then
    PATH="${PYENV_BIN}:${PATH}"
fi
if [ -f "${PYENV_BIN}/pyenv" ]; then
    PYENV="${PYENV_BIN}/pyenv"
fi
if [ -n "${PYENV}" ]; then
    eval "$(${PYENV} init -)"
    eval "$(${PYENV} virtualenv-init -)"
    export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
fi

# shellcheck disable=SC2034
set_up_gitprompt() {
    # gitprompt config
    # Set config variables first
    GIT_PROMPT_ONLY_IN_REPO=1

    # GIT_PROMPT_FETCH_REMOTE_STATUS=0   # uncomment to avoid fetching remote status
    GIT_PROMPT_IGNORE_SUBMODULES=1

    GIT_PROMPT_SHOW_UPSTREAM=1

    GIT_PROMPT_LEADING_SPACE=0
    GIT_PROMPT_START="$(echo -e '\xE2\x81\xA0')" # Invisible character
    GIT_PROMPT_START="_LAST_COMMAND_INDICATOR_"
    GIT_PROMPT_END="\n ${PS1_START}${PS1_USER}:${PS1_DIR}\n${PS1_SUFFIX}"

    # as last entry source the gitprompt script
    GIT_PROMPT_THEME_FILE=~/.dotfiles/apps/bash/Custom.bgptemplate
    # GIT_PROMPT_THEME=Custom # use custom theme specified in file GIT_PROMPT_THEME_FILE (default ~/.git-prompt-colors.sh)
    GIT_PROMPT_THEME=Custom
    # GIT_PROMPT_THEME=Solarized # use theme optimized for solarized color scheme
    [ -f "${HOME}/.dotfiles/apps/bash/subtrees/git-prompt/gitprompt.sh" ] && . "${HOME}/.dotfiles/apps/bash/subtrees/git-prompt/gitprompt.sh"
}

set_up_gitprompt
